project_name: go-rest-test
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO_VERSION=1.15
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
#    - go generate ./...
builds:


archives:
  - replacements:
      darwin: Darwin
      linux: Linux
    #      windows: Windows
    #      386: i386
    #      amd64: x86_64
#    files:
#      - ./config.toml
#      - ./config-test.toml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
